# Generated by Django 4.2.3 on 2023-07-10 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preg_check', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PregCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breeding_season', models.IntegerField()),
                ('check_date', models.DateField(auto_now_add=True)),
                ('comments', models.TextField()),
                ('preg_status', models.CharField(choices=[('O', 'Open'), ('P', 'Pregnant')], max_length=1)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preg_check.cow')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='preg_check.location')),
            ],
        ),
    ]
