# Generated by Django 4.2.3 on 2023-07-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preg_check', '0002_location_pregcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='animal_id',
            field=models.CharField(default='0001', max_length=10),
            preserve_default=False,
        ),
    ]
