# Generated by Django 4.2.3 on 2023-07-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preg_check', '0003_cow_animal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow',
            name='animal_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
