# Generated by Django 4.2.3 on 2023-10-01 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("preg_check", "0005_alter_pregcheck_comments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pregcheck",
            name="location",
        ),
        migrations.AlterField(
            model_name="pregcheck",
            name="cow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="preg_check.cow",
            ),
        ),
        migrations.DeleteModel(
            name="Location",
        ),
    ]
