# Generated by Django 4.2.3 on 2023-10-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("preg_check", "0007_alter_cow_birth_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="pregcheck",
            name="recheck",
            field=models.BooleanField(default=False),
        ),
    ]
