# Generated by Django 4.2.3 on 2023-10-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("preg_check", "0008_pregcheck_recheck"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pregcheck",
            name="preg_status",
        ),
        migrations.AddField(
            model_name="pregcheck",
            name="pregnant",
            field=models.BooleanField(default=False),
        ),
    ]
