# Generated by Django 4.2.3 on 2023-10-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("preg_check", "0009_remove_pregcheck_preg_status_pregcheck_pregnant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pregcheck",
            name="pregnant",
            field=models.BooleanField(),
        ),
    ]
