# Generated by Django 4.2.3 on 2023-10-01 15:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("preg_check", "0010_alter_pregcheck_pregnant"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pregcheck",
            old_name="pregnant",
            new_name="is_pregnant",
        ),
    ]
