# Generated by Django 4.2.3 on 2023-10-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("preg_check", "0012_alter_cow_animal_id_alter_cow_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pregcheck",
            name="is_pregnant",
            field=models.BooleanField(null=True),
        ),
    ]
