# Generated by Django 4.2.3 on 2023-10-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("preg_check", "0013_alter_pregcheck_is_pregnant"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrentBreedingSeason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("breeding_season", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="pregcheck",
            name="check_date",
            field=models.DateField(),
        ),
    ]
