# Generated by Django 4.2.3 on 2023-10-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("preg_check", "0014_currentbreedingseason_alter_pregcheck_check_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pregcheck",
            name="check_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
