# Generated by Django 4.2.3 on 2024-01-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("preg_check", "0016_alter_currentbreedingseason_breeding_season"),
    ]

    operations = [
        migrations.AddField(
            model_name="cow",
            name="eid",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
