# Generated by Django 4.2.3 on 2024-01-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("preg_check", "0017_cow_eid"),
    ]

    operations = [
        migrations.AddField(
            model_name="cow",
            name="comments",
            field=models.TextField(blank=True),
        ),
    ]
