# Generated by Django 4.2.3 on 2024-11-03 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preg_check', '0018_cow_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cow',
            old_name='animal_id',
            new_name='ear_tag_id',
        ),
        migrations.AlterUniqueTogether(
            name='cow',
            unique_together={('ear_tag_id', 'birth_year')},
        ),
    ]
