# Generated by Django 4.2.3 on 2025-05-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preg_check', '0019_rename_animal_id_cow_ear_tag_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregcheck',
            name='check_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
