# Generated by Django 4.2.3 on 2025-08-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preg_check', '0020_alter_pregcheck_check_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregcheck',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pregcheck',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
