# Generated by Django 4.2.3 on 2025-11-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preg_check', '0021_pregcheck_created_on_pregcheck_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cow',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
