# Generated by Django 4.2.3 on 2025-12-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preg_check', '0022_cow_created_on_cow_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregcheck',
            name='should_sell',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
