# Generated by Django 4.2.3 on 2026-06-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preg_check', '0023_pregcheck_should_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregcheck',
            name='should_sell',
            field=models.BooleanField(default=False),
        ),
    ]
